algoritmo "10 números soma total"
var
   numero, contador, soma: inteiro

inicio
     para contador <- 1 ate 10 faca
        escreval("Digite o",contador,"º número")
        leia(numero)

        soma <- soma + numero
     fimpara
     escreval("A soma dos números digitados é ", soma)
     
//enquanto (contador <= 10) faca
//
//contador <- contador + 1
//fimenquanto

//repita
//contador <- contador + 1
//escreval ("teste")
//ate (contador >= 10)

fimalgoritmo